[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functionsPort = 9999

[functions.environment]
SUPABASE_URL = "https://fuotedccepkedxhgtszr.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1b3RlZGNjZXBrZWR4aGd0c3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDQ4OTYsImV4cCI6MjA3MTg4MDg5Nn0.LTQSs_1y96Ry8pCET1i0DrAatzHzBRXpa4brEblSOT0"
