[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functionsPort = 9999

[functions.environment]
  FIREBASE_PROJECT_ID = "chat-app-ca53a"
  FIREBASE_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC89HOof4xI3uz6
yUeXucAlxdJhSW1stw2KxoSnV8I09ZomaUB80RINGuSkg0+MeWZXlzAGASkSIe6W
PMWmK3BsFD5yQPZX4U1D1HCDhEInozqAdkFeoUd52ZtBGtFLjEMWqS5RfDp+BoqR
iNNUubHl0Qwt/xZ+hqBVRK16+HYM8Lh/ZX9T2B3+z4cRSagEwqwv6nhoJSS2+k3I
SwpWoiWAT54fyXir8+6gd0DeunjGPQ6qAybjJpk+v19PSJOlPcTLzTJfXY4xKLg5
cfzuRtR4vU+FX0YlBZqatMs+Ejc6EjobkG2OYBkFqBkmF+OzF0XdBAXnJRVSKThq
/gPmcejfAgMBAAECggEAVw8cUOi/hn2r21qs0UPku6KbLXbq41mt9CBGU2H0WXlF
lmgNLdUYR5B6AzB7EOKIXFgM6N9VAIVAy9jhShAeorVrFjJHLjNg6Z0yX+4qmt+y
nyidMtAFQieYSFVmVDQiXwkBDcs6mgFCjA5qLFHInPYF8hVjVFWL/u1/LrbWkVv1
VUrgCUSwVbbi2B5G4qQSMAECc3+kiKER/SVpGwm3tWqt4wV9e6mqb1J/cmiZtka4
pRBuEXO3htR+iZ7IdX7T8QB4dJ3yzh7CWkxEMnbrI/vsgzsw15oLOUspq9MJkDQZ
YbrLAu39BXvy7tMYkFDeUyOpYMgV9wFx8KAwzFTnXQKBgQD8aKOAyuZrv4zcPUtS
mroKQ8eG2Ev0vfm3+dkHA8qyaVHJGp0y3Y3iHBUBRgqIoqp/oTPMVXtyHLoPTSdw
L4a/NfyR3ItpBZ+Ksep74sYeQjEyMjwTvd3699zFP0bbChq4qjWSM4qOvBPGoGMU
ccZIZe2gTnAjIMHiMZsnJDF48wKBgQC/pLEevwc1Yw6ochrAjW0Eyw69nvBG9Wx0
gK9q6MYWronKPRZCYTq0MDSYjJ5JID/pKZpCM3sDtPIeiJJ7OhG1S4JwL2j5p9y3
hcCMhbWKxJjaV6M7d8BomzKUANk6GnpM8Za0snWaQ7z8+eGYlKo82f0bSV1u5Xda
NVDKvQpLZQKBgBiDnSWcDyb10pttRIyARINMs+svxKi/bqpklKRuxNfxDKVodU4E
YIxOR+f4wnskuURuBpbY0oVxrsxfpO3rX73gY2hTMCMCDc2tm+VuT+mOajLC2Dze
mtmOCx4JGDubzp6SwWMyqElWkOEgoJ7SsfxEEgEYvSFcRBhQ0w3JIRjrAoGAY7Ec
ok3lRhRdj6qr1/a5+4BWDrYbcA5DeOdoWUj1ot7wts/IQIerrghVk/WycX/hPz1x
DXcSSv9Z5CBPcuLmS1UYaZuAFD8KRj3ByFfV9HYIvaxRMaI96SyyxuMaHWugq14R
c7ZSDwmlykOC44iSdk0/qW4kuIeN6tNJT+2+6TECgYByB4uxvpHFxmxGO3MNQMVs
k7oI1gfRcuJzd6Ablqw0XFXt+gG3sB3s2ShUnzdmOkCkCtNE1WU2QNkvPUEyElYd
QoOiS5n+lAIqwpSj4zxP8jrh0Jdw0G3Ui9Rj2UXvYCSZH/N6upof9zy1nW2tQrse
ggkRrMyhoKHWZTW8UtKyQg==
-----END PRIVATE KEY-----
"""
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@chat-app-ca53a.iam.gserviceaccount.com"
