[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functionsPort = 9999

[functions.environment]
PUSHER_APP_ID = "1977760"
PUSHER_KEY = "3925ec66482126a69fde"
PUSHER_SECRET = "918c29c07605a74e8d2b"
PUSHER_CLUSTER = "mt1"
